### ISSUE TITLE
Cannot run Android app after install library

### ISSUE THREAD

**Issue by yuraBrimit** [klarna/react-native-klarna-inapp-sdk#265]
Just use
npm install react-native-klarna-inapp-sdk --save
with autolink or manual installation

Then get following error

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '**/node_modules/react-native-klarna-inapp-sdk/android/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':react-native-klarna-inapp-sdk'.
> Plugin with id 'kotlin-android' not found.

Android/build.gradle

buildscript {
    ext {
        googlePlayServicesVersion = "+" // default: "+"
        firebaseMessagingVersion = "21.1.0" // default: "21.1.0"

        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 34

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("com.google.gms:google-services:4.3.15")
    }
}

**Comment by yuraBrimit** [comment]
UPD: Issue still not solved :(

UPD2: 
after installing kotlin in android/build.gradle I have got the following error:

Could not determine the dependencies of task ':react-native-klarna-inapp-sdk:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-klarna-inapp-sdk:debugCompileClasspath'.
   > Could not find com.klarna.mobile:sdk:2.6.19.
     Required by:
         project :react-native-klarna-inapp-sdk

**Comment by NMGuner** [comment]
Hi @yuraBrimit, we just released a version addressing issues for apps not using Kotlin. Can you try version 2.3.7 and let us know please

**Comment by yuraBrimit** [comment]
> Hi @yuraBrimit, we just released a version addressing issues for apps not using Kotlin. Can you try version 2.3.7 and let us know please


Unfortunately, still have issue with compileDebugAidl :(. But yes, kotlin error was solved.

Error: Command failed: ./gradlew app:installDevelopDebug -PreactNativeDevServerPort=8081 -PreactNativeDebugArchitectures=arm64-v8a -PreactNativeArchitectures=arm64-v8a

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-klarna-inapp-sdk:compileDebugAidl'.
Could not resolve all task dependencies for configuration ':react-native-klarna-inapp-sdk:debugCompileClasspath'.
Could not find com.klarna.mobile:sdk:2.6.19.
     Required by:
         project :react-native-klarna-inapp-sdk

**Comment by NMGuner** [comment]
Can you make sure the additional lines for maven repository configuration are added to your android build.gradle as [documented here](https://docs.klarna.com/payments/mobile-payments/integrate-with-mobile-sdk/reactnative/get-started/#adding-the-sdk-manually-warning-regarding-android-integration).
```
allprojects {
    repositories {
        // Klarna Mobile SDK CDN Repository
        maven {
            url 'https://x.klarnacdn.net/mobile-sdk/'
        }
    }
}
```

**Comment by yuraBrimit** [comment]
> Can you make sure the additional lines for maven repository configuration are added to your android build.gradle as [documented here](https://docs.klarna.com/payments/mobile-payments/integrate-with-mobile-sdk/reactnative/get-started/#adding-the-sdk-manually-warning-regarding-android-integration).
> 
> ```
> allprojects {
>     repositories {
>         // Klarna Mobile SDK CDN Repository
>         maven {
>             url 'https://x.klarnacdn.net/mobile-sdk/'
>         }
>     }
> }
> ```

yes. I've add this lines, but still the same error result (compileDebugAidl)

my build.gradle file

```
buildscript {
    ext {
        googlePlayServicesVersion = "+" // default: "+"
        firebaseMessagingVersion = "21.1.0" // default: "21.1.0"

        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 34

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("com.google.gms:google-services:4.3.15")
    }
}

allprojects {
    repositories {
        // Klarna Mobile SDK CDN Repository
        maven {
            url 'https://x.klarnacdn.net/mobile-sdk/'
        }
    }
}
```

**Comment by swamyVCN** [comment]
HI team, i did all above ,still i am having this issue , build is failing ,how to fix this

BUILD FAILED in 12s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'. > Could not find com.klarna.mobile:sdk:2.6.23. Searched in the following locations: - https://oss.sonatype.org/content/repositories/snapshots/com/klarna/mobile/sdk/2.6.23/sdk-2.6.23.pom - https://repo.maven.apache.org/maven2/com/klarna/mobile/sdk/2.6.23/sdk-2.6.23.pom - https://dl.google.com/dl/android/maven2/com/klarna/mobile/sdk/2.6.23/sdk-2.6.23.pom - https://www.jitpack.io/com/klarna/mobile/sdk/2.6.23/sdk-2.6.23.pom Required by: project :app > project :react-native-klarna-inapp-sdk * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 12s.
info Run CLI with --verbose flag for more details.
